### ISSUE TITLE
S18: As a player, I want to see the results at the end of each Reverse Challenge game section, including points awarded and audio upload statuses, so that I understand how the game's outcome was determined based on the actions and submissions of all players.

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs24-group-09/sopra-fs24-group-09-server#1]
## Acceptance Criteria:
- [ ] The system should display a summary of the game results after a game concludes, showing points awarded to each player for their answers and any bonuses for being the first, second, or third to answer correctly
- [ ] The game results page should allow players to listen to the original and reversed audios submitted during the game.
- [ ] The system should allow users to exit the summary page immediately and auto exit after a specific time period.

## Task List frontend:

- [x] #54 
- [x] #57 

## Task List backend:
- [x] #56 
- [x] #55
