### ISSUE TITLE
S2: As a logged-in user, I want to see the available services of the website that I can use after logging in, so that I can click the service and use it.

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs24-group-09/sopra-fs24-group-09-server#15]
## Acceptance Criteria

- [x] An overview/list of available services/functionalities of the website are shown after logging in.
- [x] All buttons should be displayed and clickable.
- [x] The online status becomes online so that the user can be invited by other users.
- [x] By clicking on a username in the users overview, you are redirected to a profile page
of the selected user.

## Front End
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#29
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#28
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#57
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#58

## Back End

- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#62
