### ISSUE TITLE
S3: As a newly registered user, I want to be able to set my basic user profiles (age, gender, profile picture) so that others can identify me while playing the game.

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs24-group-09/sopra-fs24-group-09-server#18]
## Acceptance Criteria
- [ ] I can edit my username and birthday, gender, introduction, and profile picture.
- [ ] It can automatically generate the creation date (and my winning rate).
- [ ] I can choose to hide my birthday, gender
- [ ] I can click the button on Profile page to ProfileEdit page.
- [ ] I can click the button back to the Profile page after editing the profile.
- [ ] I cannot edit other users' profile information

## Front End
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#30
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#31
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#32
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#48
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#65

### Back End
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#63
