### ISSUE TITLE
S16: As a player, I want a scoring system in the KAEPS game, so that i can understand how to earn points and the consequences of any gameplay actions during the game.

### ISSUE THREAD

**Issue by zihanltesla** [sopra-fs24-group-09/sopra-fs24-group-09-server#2]
## Acceptance Criteria:
- [ ] The system should clarify that the speaker will get 2 points for every correct answer submitted by other users.
- [ ] The system should clarify that the first correct answer will get highest points,the following players will get deducted points according to the sequence.
- [ ]  In case the speaker fails to upload their audio, it should be stated that each of the other players will be awarded 3 points as a penalty to the speaker for fairness

## Task List frontend:

- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#17 
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#18 

## Task List backend:
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#40 
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#39 
- [x] #52
