### ISSUE TITLE
S4: As an old user, I want to have a game lobby so that I can choose to enter a game room or create a new one

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs24-group-09/sopra-fs24-group-09-server#23]
## Acceptance Criterias

- [ ] In the game lobby, I hope that I can see all existing public game rooms created by other players
- [ ] In the game lobby, I can click an existing room to enter
- [ ] In the game lobby, I can choose to create a new room
- [ ] In the game lobby, it’s forbidden to enter a full room

## Front End
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#1
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#8
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#84

## Back End
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#25
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#27
