### ISSUE TITLE
S5: As a logged-in user, I want to create a room and edit the properties of the room so that I can customize the game

### ISSUE THREAD

**Issue by Haaaan1** [sopra-fs24-group-09/sopra-fs24-group-09-server#28]
Frontend Task:
- [ ] sopra-fs24-group-09/sopra-fs24-group-09-server#64
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#37
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#36
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#35
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#34

Backend Task:
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#69
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#71
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#102 

Acceptance Criteria:

- The room creation process should include specifying a room name and selecting game settings.
- The created room should be visible in the game lobby to all logged-in users.
