### ISSUE TITLE
S6:As a creator and an owner of a game room, I want to start the game when other players press the Ready button

### ISSUE THREAD

**Issue by Haaaan1** [sopra-fs24-group-09/sopra-fs24-group-09-server#29]
Frontend Task:

- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#38
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#39
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#51
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#52

Backend Task:

- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#74
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#75

Acceptance Criteria:

- In the game room,  I can click the ready button to be ready and I can also cancel ready
- As the creator of the room, I can only start the game after everyone is ready
