### ISSUE TITLE
S17: As a player, I want the system to automatically exit the game room and clear all temporary data after a game ends

### ISSUE THREAD

**Issue by zihanltesla** [sopra-fs24-group-09/sopra-fs24-group-09-server#3]
## Acceptance Criteria:
- [ ] Automatically exit all players from the game when all the users have been the role of speaker.
- [ ] Clear all temporary data related to the game session
- [ ]  Redirect players to the lobby after certain time period, facilitating the start of a new game

## Task List frontend:

- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#106 

## Task List backend:
- [ ] sopra-fs24-group-09/sopra-fs24-group-09-server#51 
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#50 
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#91
