### ISSUE TITLE
S12: As the player who knows the word, I want to be able to upload the audio after I finish recording

### ISSUE THREAD

**Issue by yixuan-zhou-uzh** [sopra-fs24-group-09/sopra-fs24-group-09-server#31]
## Acceptance Criteria:

- [x] After recording the audio, I can click to choose to upload my audio once in a round or I can choose not to upload until the time is up.
- [x] Only within the given time, I can upload the audio.
- [x] Without choosing to upload in the given time, the player will not have a recorded audio that other players can listen to and my round will be skipped.
- [x] Once uploading the audio, other players can listen to the audio.

## Front End Task:

- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#3
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#4
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#5
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#6
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#7

## Back End Task:

- [x] #32
- [x] #33
- [x] #34
