### ISSUE TITLE
S13: As a player, I want to be able to listen to the reverse audio repeatedly, slowly, or with pauses under my control.

### ISSUE THREAD

**Issue by yixuan-zhou-uzh** [sopra-fs24-group-09/sopra-fs24-group-09-server#38]
## Acceptance Criteria:

- [x] Only the reverse version of the word is revealed to the player.
- [x] Players can play and pause the audio many times to try to simulate it.
- [x] Players can play the audio in a slower speed to better capture the details
- [x] The audio is accessible for listening in the whole round.

## Front End Task:

- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#9
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#10
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#11
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#12

## Back End Task:

- [x] #37

**Comment by petertheprocess** [comment]
related pr for front-end: https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/pull/54
