### ISSUE TITLE
S1: As an unregistered user, I want to be able to register as a user with my chosen credentials to use services and information that are exclusively available to registered users.

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs24-group-09/sopra-fs24-group-09-server#4]
## Acceptance Criteria

- [x] Upon successful user registration, the user is redirected to the Lobby page.
- [x] Upon failure, an error is displayed, and the user is redirected (back) to the register screen. A register error can be that a username is already taken.
- [x] The creation date of a user is saved to the database record.
- [x] Logged-in users can log out and log back into their registered profile.

## Front End
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#26
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#27
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#20

## Back End
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#5
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#14
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#45
- [x] sopra-fs24-group-09/sopra-fs24-group-09-server#46
