### ISSUE TITLE
S14: As a player, I want to be able to record my simulation audio many times and play the reversed version many times to guess the word.

### ISSUE THREAD

**Issue by yixuan-zhou-uzh** [sopra-fs24-group-09/sopra-fs24-group-09-server#42]
## Acceptance Criteria:

- [x] I can click the button to record the video and click again to finish recording.
- [x] If there’s a valid recorded audio locally, I’m able to play the reverse and the original version of my recording many times.
- [x] I can delete the local audio or just re-record to overwrite the existing audio.
- [x] Only within the given time for guessing, I can record, play and try to guess the word.

## Front End Task:

- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#9
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#10
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#11
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#12
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#14
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#15
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#16
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#19

**Comment by petertheprocess** [comment]
The recorder was implementing on https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-client/issues/50
