### ISSUE TITLE
S15: As a player, I want to be able to submit my answer many times till I find the correct answers.

### ISSUE THREAD

**Issue by yixuan-zhou-uzh** [sopra-fs24-group-09/sopra-fs24-group-09-server#44]
## Acceptance Criteria:

- [ ] I can input my answer and click submit to see if it’s correct.
- [ ] Capital letters will be lowered automatically and spaces will be deleted when verifying.
- [ ] My answer won't be revealed to other players.
- [ ] Only within the given time for guessing, I can record, play and try to guess the word.

## Front End Task:

- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#25
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#24
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#23
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#22
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#21

## Back End Task:

- [x] #49 
- [x] #48 
- [x] #47
