### ISSUE TITLE
S19: As a user, I want to be able to listen to other players’ reverse audio for reference and fun. I also should be able to share my audio with others.

### ISSUE THREAD

**Issue by Zehao-Zhang** [sopra-fs24-group-09/sopra-fs24-group-09-server#78]
## Acceptance Criteria

- [x] After the simulation, guess players can share the second-reverse audio to a public channel.
- [x] This shared audio only contains the reverse edition from guess players
- [x] All players no matter speaker or guess players can listen to the shared audio in the
public channel

## Front End
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#42
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#43
- [x] sopra-fs24-group-09/sopra-fs24-group-09-client#64
